steps:
  - name: gcr.io/cloud-builders/git
    args: ["--version"]
  - name: gcr.io/cloud-builders/docker
    args: ["--version"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["--version"]
  - name: gcr.io/cloud-builders/npm
    args: ["--version"]
artifacts:
  objects:
    location: 'gs://${_BUCKET}/artifacts/$BRANCH_NAME/$REVISION_ID'
    paths: [README.md]
options:
  machineType: n1-highmem-8
